<?php
/*
* MyUCP
*/

mb_internal_encoding("UTF-8");

define('APPLICATION_DIR', dirname(__FILE__));
define('ENGINE_DIR', APPLICATION_DIR . DIRECTORY_SEPARATOR . 'engine' . DIRECTORY_SEPARATOR);
define('APP_DIR', APPLICATION_DIR . DIRECTORY_SEPARATOR . 'app' . DIRECTORY_SEPARATOR);
define('CONFIG_DIR', APPLICATION_DIR . DIRECTORY_SEPARATOR . 'configs' . DIRECTORY_SEPARATOR);
define('ASSETS_DIR', APPLICATION_DIR . DIRECTORY_SEPARATOR . 'assets' . DIRECTORY_SEPARATOR);
define('RESOURCES_DIR', APPLICATION_DIR . DIRECTORY_SEPARATOR . 'resources' . DIRECTORY_SEPARATOR);
define('EXTENSIONS_DIR', APPLICATION_DIR . DIRECTORY_SEPARATOR . 'extensions' . DIRECTORY_SEPARATOR);
define('VIEWS_DIR', RESOURCES_DIR . 'views' . DIRECTORY_SEPARATOR);
define('THEME_DIR', RESOURCES_DIR . 'views' . DIRECTORY_SEPARATOR); /* Will be deprecated in future versions */

define('ENV', APPLICATION_DIR);

/**
 * Bootstrap application
 */
require_once(ENGINE_DIR . 'app.php');